# Generated by Django 3.2.6 on 2021-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visacard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visacard',
            name='name',
        ),
        migrations.AddField(
            model_name='visacard',
            name='content',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='visacard',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
