# Generated by Django 3.2.6 on 2021-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20210820_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='logo_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
