# Generated by Django 3.2.6 on 2021-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coin_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='logo_url',
            field=models.URLField(null=True),
        ),
    ]
