# Generated by Django 3.2.6 on 2021-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_remove_coin_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='advantages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='disadvantages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='working',
            field=models.TextField(null=True),
        ),
    ]
