# Generated by Django 3.2.6 on 2021-08-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_auto_20210822_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_short_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='sparkline',
            field=models.ImageField(null=True, upload_to='media/coins'),
        ),
    ]
