# Generated by Django 3.2.6 on 2021-08-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_auto_20210823_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('acc_no', models.IntegerField(max_length=14)),
                ('quantity', models.SmallIntegerField()),
            ],
        ),
    ]
